### ISSUE TITLE
Multi-Environment Config

### ISSUE THREAD

**Issue by umkasanki** [mmikkel/CpFieldInspect-Craft#10]
Hello.
How I can disable your plugin on staging and production env?
I try to use these settings in the config/cp-field-inspect.php file
````
<?php

return [
	'dev' => [
        'enabled'       => true,
    ],
    '*' => [
    	'enabled'       => false, 
    ]  
];
````
But this leads to an error.. (see screenshot please)

![Screenshot_2019-06-22 Error](https://user-images.githubusercontent.com/496132/59960129-19e22100-94cc-11e9-8568-1b98b46d1c99.png)

Thanks for great plugin!

**Comment by mmikkel** [comment]
Hi @umkasanki – there is no `enabled` config setting in CP Field Inspect (no config settings at all, actually) which is why you get that error when you add that `config/cp-field-inspect.php` file to your project.

To achieve what you want, you can use the native [`disabledPlugins`](https://docs.craftcms.com/v3/config/config-settings.html#disabledplugins) config setting, like this (in `config/general.php`):

```php
<?php

return [
    '*' => [],
    'prod' => [
        'disabledPlugins' => ['cp-field-inspect'],
    ],
];
```

**Comment by umkasanki** [comment]
aah, sure, thanks so much!
